### ISSUE TITLE
size mismatch for lm.lm_head.weight: copying a param with shape torch.Size([50400, 4096]) from checkpoint, the shape in current model is torch.Size([50258, 4096]).

### ISSUE THREAD

**Issue by UCCME** [Aleph-Alpha/magma#31]
size mismatch for lm.lm_head.weight: copying a param with shape torch.Size([50400, 4096]) from checkpoint, the shape in current model is torch.Size([50258, 4096]).
this question is very strange. I didn't change any code, and I found that the model and the config have some mismatch.
Does anyone meet the same question?

**Comment by stefan-it** [comment]
Hi @UCCME ,

please have a look at #27. You definitely need to install forked/modified version of `transformers`, from: https://github.com/finetuneanon/transformers
