### ISSUE TITLE
Torch Size Mismatch

### ISSUE THREAD

**Issue by harshagundala** [Aleph-Alpha/magma#34]
Hey guys! 

I had a quick issue while loading Magma from the checkpoint, and I was wondering if anyone encountered or knows how to solve the problem.

`RuntimeError: Error(s) in loading state_dict for Magma:
        size mismatch for lm.lm_head.weight: copying a param with shape torch.Size([50400, 4096]) from checkpoint, the shape in current model is torch.Size([50258, 4096]).
`

It seems like the size of the checkpoint model differs from the size of the model it is expecting from the rest of the code. 

Thank you so much--this model looks super cool and I'm excited to use it!

**Comment by CoEich** [comment]
Hi,

this is likely because you use the wrong transformers version. See https://github.com/Aleph-Alpha/magma/issues/27

Best,

Constantin
